#                                                                        #
# Default subroutes configuration for the Blog package                   #
#                                                                        #

# $Id: Routes.yaml 3886 2010-02-28 17:03:50Z robert $

-
  name: 'Authentication Actions'
  uriPattern: 'authentication(/{@action})'
  appendExceedingArguments: true
  defaults:
    '@controller': 'Login'
    '@action':     'index'

-
  name: 'Logout'
  uriPattern: 'logout'
  defaults:
    '@action':    'logout'
    '@package':    'Admin'
    '@controller': 'Login'
    '@format':     'html'

-
  name: 'Admin actions'
  uriPattern: '{@action}'
  defaults:
    '@action':      'index'
    '@controller':  'Standard'
    '@format':      'html'
    
-
  name: 'Admin actions'
  uriPattern: '{@action}/{being}'
  appendExceedingArguments: true
  defaults:
    '@action':      'index'
    '@controller':  'Standard'
    '@format':      'html'
# 
# -
#   name: 'Admin actions with id'
#   uriPattern: '{@action}/{being}/{id}'
# #  appendExceedingArguments: true
#   defaults:
#     '@action':      'index'
#     '@package':     'Admin'
#     '@controller':  'Standard'
#     '@format':      'html'

-
  name: 'Documentations'
  uriPattern: 'doc/{lang}/{page}/{subpage1}'
  defaults:
    '@action':      'index'
    '@package':     'Admin'
    '@controller':  'Doc'
    '@format':      'html'
    '@lang':        'en'
    '@doc':         'Manual'
    '@page':        '1_Index'

-
  name: 'Documentations'
  uriPattern: 'doc/{lang}/{page}'
  defaults:
    '@action':      'index'
    '@package':     'Admin'
    '@controller':  'Doc'
    '@format':      'html'
    '@lang':        'en'
    '@doc':         'Manual'
    '@page':        '1_Index'

-
  name: 'Documentations'
  uriPattern: 'doc/{lang}'
  defaults:
    '@action':      'index'
    '@package':     'Admin'
    '@controller':  'Doc'
    '@format':      'html'
    '@lang':        'en'
    '@doc':         'Manual'
    '@page':        'index.html'
